############################################
## MAIN parameters
############################################

## Path to meta-file with RAW TUMOR samples (following columns are required: sample, platform, fq1/fq2 (tab separated))
meta: /data/SP/home/ieo5398/TOSCA/metafile/WES/WES_Derenzini.txt
## Path to the OUTPUT directory            
output: /scratch/SP/Derenzini/WES/DLBCL_new

############################################
## OPTIONAL (HIGHLY recommended for WES)
############################################

## NORMAL PANEL
## Path to meta-file with RAW NORMAL samples
## Activate this step ONLY if you have at least 5 normal samples for PureCN filtering and tumor purity / ploidy estimation (https://bioconductor.org/packages/release/bioc/html/PureCN.html)
## These NORMAL samples ARE NOT required to be PATIENT-matched to the tumor samples, but they need to be PROCESSED-matched (same assay run through the same alignment pipeline, ideally sequenced in the same lab)

## Path to meta-file with RAW NORMAL samples (following columns are required: id, platform, fq1/fq2 (tab separated))
meta_N: /data/SP/home/ieo5398/TOSCA/metafile/WES/WES_N_Derenzini.txt # <<< Uncomment this line to ACTIVATE NORMAL step!
## Path to Normal OUTPUT directory
normDB: /scratch/SP/Derenzini/WES/HD

## PureCN parameters (only if you provided meta-file of RAW NORMAL samples and activate PureCN step)
kmer: 100 #kmer size for mappability file (76 or 100)
baits: /scratch/SP/Derenzini/WES/Salive_old/S31285117_Padded.bed
mappability:
  GRCh38: "https://s3.amazonaws.com/purecn/GCA_000001405.15_GRCh38_no_alt_analysis_set"
  GRCh37: "https://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeMapability/wgEncodeCrgMapabilityAlign"

############################################
## ADDITIONAL parameters
############################################

## Number of cores
ncores: 14

## Genome reference
ref:
## ensembl species name
  species: homo_sapiens
## ensembl release
  release: 104  # The most recent release of human genome is 104 (May 2021)
## genome build 
  build: GRCh38 # GRCh38/GRCh37
## snpEff annotation
  snpeff_db: GRCh38.99
##
## Quality and target filtering
filtering:
## Provide BED file if you have TARGET sequencing
  restrict-regions: /scratch/SP/Derenzini/WES/Salive_old/S31285117_Covered.bed
## Minimum read depth to call a variant (100-250x suggested)   
  min_depth: 100
## Minimum variant allele frequency (5% suggested)  
  vaf: 0.05 
##
## Database
##
database_url:
  GRCh38:
    germline:
      1000G: "http://ftp.ensembl.org/pub/current_variation/vcf/homo_sapiens/1000GENOMES-phase_3.vcf.gz"
      ESP: "http://evs.gs.washington.edu/evs_bulk_data/ESP6500SI-V2-SSA137.GRCh38-liftover.snps_indels.vcf.tar.gz"
      ClinVar: "https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz"
      ExAC: resources/database/GRCh38/GRCh38.ExAC.vcf.gz
      PON: resources/pon/GRCh38/1000G_PON.vcf.gz
    somatic:
      Cosmic: "http://ftp.ensembl.org/pub/current_variation/vcf/homo_sapiens/homo_sapiens_somatic.vcf.gz"
  GRCh37:
    germline:
      1000G: "http://ftp.ensembl.org/pub/grch37/current/variation/vcf/homo_sapiens/1000GENOMES-phase_3.vcf.gz"
      ESP: "http://evs.gs.washington.edu/evs_bulk_data/ESP6500SI-V2-SSA137.GRCh38-liftover.snps_indels.vcf.tar.gz"
      ClinVar: "https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/clinvar.vcf.gz"
      ExAC: resources/database/GRCh37/GRCh37.ExAC.vcf.gz
      PON: resources/pon/GRCh37/1000G_PON.vcf.gz
    somatic:
      Cosmic: "http://ftp.ensembl.org/pub/grch37/current/variation/vcf/homo_sapiens/homo_sapiens_somatic.vcf.gz"  
##
params:
  trimmomatic:
    pe:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "LEADING:20"
        - "TRAILING:20"
        - "SLIDINGWINDOW:3:15"
        - "AVGQUAL:20"
        - "MINLEN:35"
        - "TOPHRED33"
    se:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "LEADING:20"
        - "TRAILING:20"
        - "SLIDINGWINDOW:3:15"
        - "AVGQUAL:20"
        - "MINLEN:35"
        - "TOPHRED33"

## Software
bamstats: resources/software/bamstats04.jar 
gatk3: resources/software/GenomeAnalysisTK.jar    
     
FQ: ["1", "2"]
